title: My Jekyll Site
description: A simple website powered by Jekyll
theme: minima  # You can change to another supported theme
baseurl: ""  # Leave empty for GitHub Pages
url: "https://avelosa-segment.github.io"  # Replace with your GitHub username
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed  # RSS feed support

exclude:
  - node_modules
  - vendor
